void avx2_tests_init(size_t cpus, _Atomic(uint64_t)* errors);

void avx2_basic_tests(void* const mem, const size_t size);
void avx2_march(void* const mem, const size_t size);
void avx2_random_inversions(void* const mem, const size_t size);
void avx2_moving_inversions_left_64(void* const mem, const size_t size);
void avx2_moving_inversions_right_32(void* const mem, const size_t size);
void avx2_moving_inversions_left_16(void* const mem, const size_t size);
void avx2_moving_inversions_right_8(void* const mem, const size_t size);
void avx2_moving_inversions_left_4(void* const mem, const size_t size);
void avx2_moving_saturations_right_16(void* const mem, const size_t size);
void avx2_moving_saturations_left_8(void* const mem, const size_t size);
void avx2_addressing(void* const mem, const size_t size);
void avx2_sgemm(void* const mem, const size_t size);
void avx2_walking_1(void* const mem, const size_t size);
void avx2_walking_0(void* const mem, const size_t size);
void avx2_checkerboard(void* const mem, const size_t size);
void avx2_address_line_test(void* const mem, const size_t size);
void avx2_anti_patterns(void* const mem, const size_t size);
void avx2_inverse_data_patterns(void* const mem, const size_t size);
